import fs from 'node:fs'
import path from 'node:path'
import type { ReferenceSyncConfig } from '../../../shared/referenceSync'
import { listReferenceFiles, referenceSummary } from '../refSync/referenceFiles'
import { refTitle } from '../refSync/refFrontmatter'

/** Per-line cap, matching the INDEX.md router's own convention. */
const SUMMARY_MAX = 160

/** Entry cap: this index is appended to EVERY turn's system prompt, so a large library must
 *  degrade to a pointer rather than growing the prompt without bound. */
const MAX_ENTRIES = 60

/**
 * Lead line of the prompt-visible reference index. Registered as `session.reference-index-lead`.
 *
 * References were synced, indexed and browsable but never advertised to an agent: the system
 * prompt carried a skill index and a memory index and nothing for references, and the case
 * CLAUDE.md named six tool conventions without mentioning them. So every reference read "never
 * read" in usage stats — correctly, because no agent had ever been told they existed. This is
 * the positive instruction. It says to OPEN the file rather than to infer from the title,
 * because a title is not the knowledge.
 */
export const REFERENCE_INDEX_LEAD =
  'Team references: durable knowledge your team wrote down once so nobody has to re-derive it — product areas, log signatures, tool recipes, known issues. When one looks relevant to this case, open it with the Read tool at the path below; do not infer its contents from the title. They are read-only.'

/**
 * The prompt-visible index of team references, built in memory from the directory.
 *
 * Deliberately NOT read off references/INDEX.md. That file is regenerated by writers, and a
 * writer missed in future would silently poison what every agent is told — which is exactly the
 * failure this index exists to fix. Both artifacts come from the same directory through the same
 * walk, so they agree whenever the file is fresh.
 */
export function buildReferenceIndex(
  refsDir: string,
  config: ReferenceSyncConfig,
  resolve?: (id: string) => string
): string {
  const files = listReferenceFiles(refsDir)
  if (files.length === 0) return ''
  const rules = config.spaces.flatMap((s) => s.routingRules)
  const shown = files.slice(0, MAX_ENTRIES)
  const lines: string[] = []
  for (const rel of shown) {
    // A reference that vanishes between the walk and this read must not kill session
    // construction — this runs on the CaseSession constructor path.
    let raw: string
    try {
      raw = fs.readFileSync(path.join(refsDir, rel), 'utf8')
    } catch {
      continue
    }
    const title = refTitle(raw) ?? path.basename(rel).replace(/\.md$/, '')
    const summary = referenceSummary(raw).slice(0, SUMMARY_MAX)
    const keywords = [...new Set(rules.filter((r) => r.target === rel).flatMap((r) => r.keywords))]
    lines.push(
      `- ${rel} — ${title}` +
        (summary ? `: ${summary}` : '') +
        (keywords.length ? ` · keywords: ${keywords.join(', ')}` : '')
    )
  }
  if (lines.length === 0) return ''
  const lead = resolve ? resolve('session.reference-index-lead') : REFERENCE_INDEX_LEAD
  const withheld = files.length - shown.length
  return [
    lead,
    `Directory: ${refsDir}`,
    ...lines,
    ...(withheld > 0 ? [`- …and ${withheld} more in that directory.`] : [])
  ].join('\n')
}
