export const IPC = {
  casesCreate: 'cases:create',
  casesList: 'cases:list',
  caseCost: 'cases:cost',
  caseReadFindings: 'cases:read-findings',
  casesSetStatus: 'cases:set-status',
  evidenceIngest: 'evidence:ingest',
  /** renderer → main: ingest in-memory bytes (pasted screenshot, dropped file). */
  evidenceIngestContent: 'evidence:ingest-content',
  evidenceList: 'evidence:list',
  evidenceRead: 'evidence:read',
  evidenceReadSnippet: 'evidence:read-snippet',
  evidenceChanged: 'evidence:changed',
  textdocOpen: 'textdoc:open',
  textdocLines: 'textdoc:lines',
  textdocSearch: 'textdoc:search',
  textdocCancelSearch: 'textdoc:cancel-search',
  /** main → renderer: streaming search result batches for the viewer find bar. */
  textdocSearchHits: 'textdoc:search-hits',
  /** main → renderer: lazy line-index build progress { key, fraction }. */
  textdocIndexProgress: 'textdoc:index-progress',
  searchQuery: 'search:query',
  chatSearch: 'chat:search',
  agentSend: 'agent:send',
  agentInterrupt: 'agent:interrupt',
  agentRespond: 'agent:respond',
  agentAuthStatus: 'agent:auth-status',
  agentAuthChanged: 'agent:auth-changed',
  providerStatuses: 'providers:statuses',
  providerRefresh: 'providers:refresh',
  providersChanged: 'providers:changed',
  agentPreflight: 'agent:preflight',
  agentEventChannel: 'agent:event',
  agentHistory: 'agent:history',
  sessionsList: 'sessions:list',
  sessionsCreate: 'sessions:create',
  sessionsRename: 'sessions:rename',
  sessionsSetModel: 'sessions:set-model',
  workspacesPick: 'workspaces:pick',
  workspacesLink: 'workspaces:link',
  workspacesUnlink: 'workspaces:unlink',
  workspacesList: 'workspaces:list',
  workspacesReadSnippet: 'workspaces:read-snippet',
  workspacesReadText: 'workspaces:read-text',
  /** main → renderer broadcast: a case's workspace state changed (e.g. the agent
   *  materialized a worktree) — repo chips and repo snippets should refresh. */
  workspacesChanged: 'workspaces:changed',
  skillsList: 'skills:list',
  skillsDeleteUser: 'skills:delete-user',
  settingsGet: 'settings:get',
  settingsPatch: 'settings:patch',
  settingsChanged: 'settings:changed',
  settingsProbeTools: 'settings:probe-tools',
  settingsPickPath: 'settings:pick-path',
  settingsReveal: 'settings:reveal',
  settingsSetDataRoot: 'settings:set-data-root',
  connectorsGet: 'connectors:get',
  connectorsPatch: 'connectors:patch',
  connectorsChanged: 'connectors:changed',
  connectorsTest: 'connectors:test',
  connectorsOauth: 'connectors:oauth',
  secretsSet: 'secrets:set',
  secretsHas: 'secrets:has',
  secretsDelete: 'secrets:delete',
  healthList: 'health:list',
  healthRun: 'health:run',
  healthResult: 'health:result',
  sourceControlStatus: 'sourcecontrol:status',
  appOpenExternal: 'app:open-external',
  jiraPreview: 'jira:preview',
  jiraCreateCase: 'jira:create-case',
  jiraIngestAttachments: 'jira:ingest-attachments',
  jiraRefreshCase: 'jira:refresh-case',
  jiraMarkReviewed: 'jira:mark-reviewed',
  jiraSyncAll: 'jira:sync-all',
  jiraSyncProgress: 'jira:sync-progress',
  jiraAttachmentProgress: 'jira:attachment-progress',
  jiraSetAttachmentSelection: 'jira:set-attachment-selection',
  jiraOpenIssue: 'jira:open-issue',
  accessGet: 'access:get',
  accessPatch: 'access:patch',
  accessChanged: 'access:changed',
  memoryTopics: 'memory:topics',
  memoryRead: 'memory:read',
  memoryWrite: 'memory:write',
  memoryDelete: 'memory:delete',
  memoryAudit: 'memory:audit',
  memoryArchive: 'memory:archive',
  memoryRestore: 'memory:restore',
  bundleExport: 'bundle:export',
  bundleInspect: 'bundle:inspect',
  bundleImport: 'bundle:import',
  workspacesRefs: 'workspaces:refs',
  hivemindGet: 'hivemind:get',
  hivemindCheck: 'hivemind:check',
  hivemindSync: 'hivemind:sync',
  hivemindInstall: 'hivemind:install',
  hivemindUninstallSkill: 'hivemind:uninstall-skill',
  hivemindUninstallReference: 'hivemind:uninstall-reference',
  hivemindClaimReference: 'hivemind:claim-reference',
  hivemindDiff: 'hivemind:diff',
  hivemindPushPreview: 'hivemind:push-preview',
  hivemindPush: 'hivemind:push',
  proposalsList: 'proposals:list',
  proposalsAccept: 'proposals:accept',
  proposalsReject: 'proposals:reject',
  filesList: 'files:list',
  filesRead: 'files:read',
  filesOpen: 'files:open',
  filesReveal: 'files:reveal',
  filesChanged: 'files:changed',
  evidenceParsing: 'evidence:parsing',
  packsArtifactMeta: 'packs:artifact-meta',
  packsReferenceRouting: 'packs:reference-routing',
  packsList: 'packs:list',
  packsPickBundle: 'packs:pick-bundle',
  packsInspect: 'packs:inspect',
  packsInstall: 'packs:install',
  packsUninstall: 'packs:uninstall',
  packsRelaunch: 'packs:relaunch',
  packsChanged: 'packs:changed',
  refsyncGet: 'refsync:get',
  refsyncValidateSpace: 'refsync:validate-space',
  refsyncChildren: 'refsync:children',
  refsyncSaveSpace: 'refsync:save-space',
  refsyncRemoveSpace: 'refsync:remove-space',
  refsyncSync: 'refsync:sync',
  refsyncPrune: 'refsync:prune',
  refsyncApplyDrafts: 'refsync:apply-drafts',
  refsyncReadRef: 'refsync:read-ref',
  refsyncSearchRefs: 'refsync:search-refs',
  refsyncChanged: 'refsync:changed',
  refsyncProgress: 'refsync:progress',
  metricsGlobal: 'metrics:global',
  metricsCase: 'metrics:case',
  usageStats: 'usage:stats',
  findingsList: 'findings:list',
  findingsReview: 'findings:review',
  casesDelete: 'cases:delete',
  onboardingSeedSample: 'onboarding:seed-sample',
  evidenceDelete: 'evidence:delete',
  evidenceScan: 'evidence:scan',
  sessionsDelete: 'sessions:delete',
  findingsClear: 'findings:clear',
  graphBuild: 'graph:build',
  graphStatus: 'graph:status',
  graphInstall: 'graph:install',
  graphBuilding: 'graph:building',
  graphChanged: 'graph:changed',
  graphProgress: 'graph:progress',
  // — panels (webPanel host; 3a-2) —
  panelsList: 'panels:list',
  panelsOpen: 'panels:open',
  panelsClose: 'panels:close',
  panelsFocus: 'panels:focus',
  panelsPopOut: 'panels:pop-out',
  panelsDockBack: 'panels:dock-back',
  panelsSetTheme: 'panels:set-theme',
  panelsChanged: 'panels:changed',
  // main→renderer: select this panel (agent-opened panels aren't selected client-side)
  panelsActivate: 'panels:activate',
  panelsTheme: 'panels:theme',
  panelsGetCaseContext: 'panels:get-case-context',
  panelsRequestEvidence: 'panels:request-evidence',
  panelsReadEvidence: 'panels:read-evidence',
  panelsListCaseEvidence: 'panels:list-case-evidence',
  // — panels · docking UX (3a-3) —
  panelsDecls: 'panels:decls',
  panelsSetBounds: 'panels:set-bounds',
  panelsSetVisible: 'panels:set-visible',
  panelsCloseCase: 'panels:close-case',
  // — panels · write bridge (3b-1) —
  panelsCite: 'panels:cite',
  panelsEmitFinding: 'panels:emit-finding',
  panelsSendToAgent: 'panels:send-to-agent',
  /** main → main-renderer broadcast: a panel cited evidence; the citations tray adds a chip. */
  panelsCiteAdded: 'panels:cite-added',
  /** main → main-renderer broadcast: a panel staged text via sendToAgent; the composer draft is set. */
  panelsDraft: 'panels:draft',
  // — panels · evidence ingest (3d-2) —
  panelsIngestEvidence: 'panels:ingest-evidence',
  /** main → main-renderer broadcast: a panel ingested evidence; refresh the case's evidence list. */
  panelsEvidenceIngested: 'panels:evidence-ingested',
  // — panels · command dispatch (3b-2) —
  /** main → panel: deliver a correlated command request (PanelHost.dispatchToPanel). */
  panelsCommand: 'panels:command',
  /** panel → main: reply to a dispatched command (routes to PanelHost.resolveCommand). */
  panelsCommandResult: 'panels:command-result',
  // — external apps (3c) —
  externalAppsList: 'external-apps:list',
  externalAppsOpen: 'external-apps:open',
  externalAppsStop: 'external-apps:stop',
  // — case-close distillation (part 3a) —
  distillChanged: 'distill:changed',
  distillStatus: 'distill:status',
  distillRetry: 'distill:retry',
  distillRedistill: 'distill:redistill',
  distillSimilar: 'distill:similar'
} as const
